"""存储层:SQLite + SQLAlchemy。"""

from .db import init_db, make_engine, session_scope
from .messages import append_message, list_messages
from .models import (
    Base,
    ExternalAccount,
    InboundEvent,
    Message,
    Note,
    PendingMessage,
    ProfileClaim,
    ProfileField,
    Reminder,
    User,
    UserPersona,
    UserUsage,
)
from .queue import drain_pending, enqueue, list_undelivered
from .users import (
    ExternalAccountRecord,
    ResolvedPersonaRecord,
    UserPersonaRecord,
    UserRecord,
    UserSummaryRecord,
    begin_inbound_event,
    bind_external_account,
    create_user,
    delete_user_persona,
    ensure_local_user,
    finish_inbound_event,
    get_or_create_external_user,
    get_user,
    get_user_persona,
    increment_usage,
    list_user_summaries,
    resolve_external_account,
    resolve_user_persona,
    set_user_daily_limit,
    set_user_persona,
    set_user_status,
    usage_count_today,
)

__all__ = [
    "Base",
    "ExternalAccountRecord",
    "ExternalAccount",
    "InboundEvent",
    "Message",
    "Note",
    "PendingMessage",
    "ProfileClaim",
    "ProfileField",
    "Reminder",
    "ResolvedPersonaRecord",
    "User",
    "UserPersona",
    "UserPersonaRecord",
    "UserRecord",
    "UserSummaryRecord",
    "UserUsage",
    "append_message",
    "begin_inbound_event",
    "bind_external_account",
    "create_user",
    "delete_user_persona",
    "drain_pending",
    "enqueue",
    "ensure_local_user",
    "finish_inbound_event",
    "get_or_create_external_user",
    "get_user",
    "get_user_persona",
    "increment_usage",
    "init_db",
    "list_user_summaries",
    "list_messages",
    "list_undelivered",
    "make_engine",
    "resolve_external_account",
    "resolve_user_persona",
    "session_scope",
    "set_user_daily_limit",
    "set_user_persona",
    "set_user_status",
    "usage_count_today",
]
